# SPDX-License-Identifier: MPL-2.0

[package]
name = "zeroconfgetter"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
tokio = { version = "1.41", features = ["net", "io-util"] }
zeroconf-tokio = "0.2"
