# SPDX-License-Identifier: MPL-2.0

[package]
name = "zeroconfgetter"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
mdns-sd = "0.13"
phf = { version = "0.11", features = ["macros"] }
tokio = { version = "1.44", features = [
    "net",
    "io-util",
    "rt-multi-thread",
    "macros",
    "sync",
] }
